Procfile
app.json
app.py
requirements.txt

Prepares for Heroku deployment of a non-functional Python application.
Part of #3.

Stubbed in basic Flask Hello World app

---

app.json
app.pgsql
app.py
requirements.txt

Trying to verify database setup and Heroku pipeline. Part of #3.

Added single-feature Postgres table

---

.travis.yml
CDTADPQ/web/__init__.py
app.json

Experiment with various SMS add-ons

---

CDTADPQ/web/__init__.py
CDTADPQ/web/templates/about.html
CDTADPQ/web/templates/confirmation.html
CDTADPQ/web/templates/index.html
CDTADPQ/web/templates/layout.html
CDTADPQ/web/templates/register.html
CDTADPQ/web/test_init.py

Creating templates to use for:

UI templates

---

CDTADPQ/web/__init__.py

Fixed encoding lameness

---

.travis.yml
CDTADPQ/data/test_users.py
CDTADPQ/data/users.py
CDTADPQ/web/__init__.py
CDTADPQ/web/templates/confirmation.html
CDTADPQ/web/templates/error-auth.html
CDTADPQ/web/templates/layout.html
CDTADPQ/web/test_init.py

Part of #18: makes it possible for a user to see that they are logged in.

Add user logged-in state

---

CDTADPQ/web/__init__.py
CDTADPQ/web/templates/registered.html
CDTADPQ/web/test_init.py

Added PIN code check that actually works

---

CDTADPQ/web/templates/layout.html
CDTADPQ/web/templates/sent.html

Replaced hardcoded paths with Flask’s way of building URLs.

Updated links to use Flask definitions

---

CDTADPQ/data/collect.py
CDTADPQ/data/test_collect.py
test.py

Need to make a scheduled task to call `python -m CDTADPQ.data.collect` regularly. Closes #33.

Added new script for collecting real data

---

CDTADPQ/data/test_zipcodes.py
CDTADPQ/data/zipcodes.py
CDTADPQ/web/__init__.py
CDTADPQ/web/templates/layout.html
CDTADPQ/web/templates/register.html
CDTADPQ/web/test_init.py
test.py

Added zip code geolocation support

---

CDTADPQ/data/scripts/006-add-user-email.pgsql

Added users.email_address column

---

CDTADPQ/data/scripts/007-add-user-emergencies.pgsql

Added users.emergencies column

---

CDTADPQ/web/__init__.py
CDTADPQ/web/templates/admin.html
CDTADPQ/web/templates/send-alert.html
app.json

Added username/password for admin area

---

CDTADPQ/data/scripts/008-alter-user-emergency-column-name.pgsql

Related to issue https://github.com/VeryLittleGravitas/CDTADPQ/issues/58

Rename column for future clarity

---

CDTADPQ/data/notify.py
CDTADPQ/data/test_notify.py
CDTADPQ/data/wildfires.py

Default to 50 miles; configure with `RADIUS_MILES` environment variable. Closes #74.

Refine notify.get_users_to_notify() query with a search radius

---

CDTADPQ/data/scripts/011-create-quake_points.pgsql
CDTADPQ/data/scripts/012-create-flood_polys.pgsql

Pre-requisite for https://github.com/VeryLittleGravitas/CDTADPQ/pull/84 and forthcoming Floods PR.

Added flood_polys and quake_points tables

---

readme.md

Added answers to technical requirements.

Update readme requirements

---

CDTADPQ/web/templates/layout.html

#85 
Added code snippet for analytics, as requested, to the layout template.

Fixes #85 Added GA code snippet

---

CDTADPQ/data/collect.py
CDTADPQ/data/earthquakes.py
CDTADPQ/data/test_collect.py
CDTADPQ/data/test_earthquakes.py
test.py

Add Earthquake data

---

CDTADPQ/data/collect.py
CDTADPQ/data/floods.py
CDTADPQ/data/test_collect.py
CDTADPQ/data/test_floods.py
test.py

Added Flooding data source

---

CDTADPQ/web/templates/send-alert.html
CDTADPQ/web/templates/sent.html

Fixes #82 
Just text changes. Nothing functional.

Simplify messaging on send and sent pages

---

CDTADPQ/data/test_users.py
CDTADPQ/data/users.py
CDTADPQ/web/__init__.py
CDTADPQ/web/templates/includes/settings.html

Added button to Delete User

---

CDTADPQ/web/templates/layout.html

Contact options

---

CDTADPQ/data/scripts/013-alter-users-add-notification-types.pgsql

Related to https://github.com/VeryLittleGravitas/CDTADPQ/issues/58

Add notification types so users can pick the type of messages they get

---

CDTADPQ/data/notify.py
CDTADPQ/data/test_notify.py
CDTADPQ/data/test_users.py
CDTADPQ/data/users.py
CDTADPQ/web/__init__.py
CDTADPQ/web/templates/admin.html
CDTADPQ/web/templates/send-alert.html
CDTADPQ/web/templates/sent.html
CDTADPQ/web/test_init.py

Related to https://github.com/VeryLittleGravitas/CDTADPQ/issues/90
and https://github.com/VeryLittleGravitas/CDTADPQ/issues/41
Currently does not use the emergency/non-emergency radio button to filter users. Users don't have the ability to set notification settings yet.

Allow an admin to send notifications to all users via a form

---

CDTADPQ/web/__init__.py
CDTADPQ/web/templates/admin-sent.html

Here's a template for you to merge!

Previously on California Alerts

---

CDTADPQ/web/templates/login.html

Made the login page copy friendlier to explain what you can do when you login and that you need your phone number and a PIN code to login.

Updated copy for the Login template

---

CDTADPQ/web/templates/admin.html

Updated the copy for the Admin send-alert user interface.

Admin send alert copy changes

---

CDTADPQ/web/__init__.py
CDTADPQ/web/templates/admin-sent.html
CDTADPQ/web/templates/admin.html
CDTADPQ/web/templates/includes/log.html
CDTADPQ/web/templates/sent.html

Added a button from the admin dashboard to get to the log and included that log as a seperate file in both locations we want to see it.

Sent log links

---

CDTADPQ/web/__init__.py
CDTADPQ/web/static/api-doc.yaml
CDTADPQ/web/templates/api-index.html

Closes #93.
Should be visible at https://vlg-ctdadpq-pr-125.herokuapp.com/api

Added Swagger API docs for the one API method we have

---

readme.md

Lots of technical documentation changes and edits for clarity.

Update readme documentation

---

CDTADPQ/web/templates/index.html

I have used words to describe what the map is so that users are not confused.

Homepage map copy

---

CDTADPQ/data/scripts/014-create-notifications-log-table.pgsql

Related: https://github.com/VeryLittleGravitas/CDTADPQ/issues/91

Add notifications table

---

CDTADPQ/data/earthquakes.py
CDTADPQ/data/floods.py
CDTADPQ/web/__init__.py

Part of #60, follow-on to #126.

Add floods and earthquakes to the map

---

CDTADPQ/data/notify.py
CDTADPQ/data/test_notify.py
CDTADPQ/data/test_wildfires.py
CDTADPQ/data/wildfires.py
CDTADPQ/web/__init__.py

Related to https://github.com/VeryLittleGravitas/CDTADPQ/issues/91

Log notifications so we can later display notification history

---

CDTADPQ/data/stats.py
CDTADPQ/data/test_stats.py
test.py

related https://github.com/VeryLittleGravitas/CDTADPQ/issues/91

Helper method to fetch notification log rows

---

readme.md

We should now be at 1,923 words in README.md

Reduced readme.md wordcount

---

readme.md

I forgot to document how notifications are sent, which seems pretty critical I suppose.

Remembered to explain how we send notifications.

---

CDTADPQ/data/notifications.py
CDTADPQ/data/notify.py
CDTADPQ/data/test_notifications.py
CDTADPQ/data/test_notify.py
CDTADPQ/data/test_users.py
CDTADPQ/data/users.py
CDTADPQ/web/__init__.py
test.py

Sends emails to people if applicable, and reorganizes some code around SMS too.
Closes #81. Closes #73.

Send Emails to people

---

CDTADPQ/data/test_users.py
CDTADPQ/data/users.py
CDTADPQ/web/__init__.py
CDTADPQ/web/templates/includes/settings.html

related https://github.com/VeryLittleGravitas/CDTADPQ/issues/90

Send non-emergency notifications to people who want them

---

CDTADPQ/data/floods.py
CDTADPQ/data/test_floods.py

Added code to dedupe floods
